/*
 * Generates payload/webroot/tokens.css: a full Material 3 colour scheme (light
 * and dark) derived from one seed colour, the way Material You would derive it
 * from a wallpaper. The WebView cannot see the device's wallpaper palette, so
 * the seed is fixed here and the palette is generated, committed and reviewed.
 *
 * Change SEED and re-run to re-theme; nothing else changes, because the
 * components read --md-sys-color-* directly.
 */
import { themeFromSourceColor, argbFromHex, hexFromArgb } from '@material/material-color-utilities';

const SEED = '#4c6a92';

const theme = themeFromSourceColor(argbFromHex(SEED));

const kebab = (name) => '--md-sys-color-' + name.replace(/[A-Z]/g, (c) => '-' + c.toLowerCase());

/* material-color-utilities 0.4 exposes the roles as prototype getters, and only
 * the classic set. The newer surface-container roles are derived here from the
 * neutral palette, using the tonal values from the Material 3 spec. */
const CONTAINER_TONES = {
  light: { surfaceDim: 87, surfaceBright: 98, surfaceContainerLowest: 100, surfaceContainerLow: 96,
           surfaceContainer: 94, surfaceContainerHigh: 92, surfaceContainerHighest: 90 },
  dark:  { surfaceDim: 6,  surfaceBright: 24, surfaceContainerLowest: 4,   surfaceContainerLow: 10,
           surfaceContainer: 12, surfaceContainerHigh: 17, surfaceContainerHighest: 22 },
};

function roles(scheme, mode) {
  const names = Object.getOwnPropertyNames(Object.getPrototypeOf(scheme))
    .filter((name) => typeof scheme[name] === 'number');
  const entries = names.map((name) => [name, scheme[name]]);
  for (const [name, tone] of Object.entries(CONTAINER_TONES[mode])) {
    entries.push([name, theme.palettes.neutral.tone(tone)]);
  }
  // legacy name kept for themes that still read it
  entries.push(['surfaceTint', scheme.primary]);
  return entries;
}

const block = (mode) => roles(theme.schemes[mode], mode)
  .map(([name, argb]) => `  ${kebab(name)}: ${hexFromArgb(argb)};`)
  .join('\n');

const css = `/* Generated by tools/webui/gen-tokens.mjs from seed ${SEED} - do not edit by hand.
   Regenerate with: cd tools/webui && bun install && bun run gen-tokens.mjs */
:root {
  color-scheme: light dark;
${block('light')}
}

@media (prefers-color-scheme: dark) {
  :root {
${block('dark')}
  }
}
`;

const target = new URL('../../payload/webroot/tokens.css', import.meta.url);
await Bun.write(target, css);
console.log('tokens.css: ' + (css.match(/--md-sys-color-/g) || []).length + ' tokens -> ' + target.pathname);
