#!/bin/sh
# Fake ifconfig for the daemon integration tests.

echo "wlan0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500"
echo "        inet 192.168.1.23  netmask 255.255.255.0  broadcast 192.168.1.255"
echo "        inet6 fe80::1  prefixlen 64  scopeid 0x20<link>"
